name: Performance

on:
  workflow_dispatch:
  schedule:
    - cron: "3 0 * * 5"

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'grouparoo/www.grouparoo.com' }}
    steps:
      - name: echo actor
        run: |
          echo ${{github.actor}}
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
      - name: Calculate performance
        run: |
          ./scripts/performance_action
      - name: Load Comment Markdown
        id: comment
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.lighthouseci/comment.md
      - name: Echo Comment Markdown
        run: echo "${{ steps.comment.outputs.content }}"
      - name: Post Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 539 # https://github.com/grouparoo/www.grouparoo.com/discussions/537
          body: "${{ steps.comment.outputs.content }}"
