name: update-branch

on: [pull_request, pull_request_target]

jobs:
  update-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
      - name: Update files
        run: |
          ./scripts/github_action
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updating things automatically
          commit_user_name: Grouparoo Bot
          commit_user_email: hello@grouparoo.com
          commit_author: Grouparoo Bot <hello@grouparoo.com>
          branch: ${{ github.head_ref }}
